@Restaurants.Api_HostAddress = https://localhost:7182
# Accept: application/json

####

GET {{Restaurants.Api_HostAddress}}/api/restaurants

###

GET {{Restaurants.Api_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.Api_HostAddress}}/api/restaurants
Content-Type: application/json
{
  
}


